import { StyleSheet } from "react-native";
import { shadow } from "react-native-paper";

const themeColor = '#FFC0CB'
const vsrs = "#222222"
const understandMargin = 200
export const allTheStyles = StyleSheet.create({
  saveButton: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 190,
  },
  saveButtonNew: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    fontStyle: "italic",
    backgroundColor: themeColor,
    fontWeight: "bold",
    height: 440,
  },
  leTitleButton: {
    top: 20,
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 50,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 180,
    color: 'white'
  },
  logo: {
  
    width: '130%',
    height: 1000,
    position: 'absolute',
    top: -400,
    right: 17
  },
  radialEx: {
    width: 450,
    height: 300,
    position: 'absolute',
    top: -50,
    right: -10
  },
  gpt : {
    flex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  hite: {
    height: 200
  },
  basicListItems : {
    textAlignVertical: "center",
    textAlign: "left",
    fontSize: 30,
    color: "black",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 50,
  },
  chartTheme : {
    axis: {
      style: {
        tickLabels: {
          // this changed the color of my numbers to white
          fill: 'white',
        },
      },
    },
  },
  basicListItemsGreen : {
    textAlignVertical: "center",
    textAlign: "left",
    fontSize: 30,
    color: "green",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 50,
  },
  basicListItemsBlue : {
    textAlignVertical: "center",
    textAlign: "left",
    fontSize: 30,
    color: "blue",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 50,
  },
  addVariant : {
    textAlignVertical: "center",
    textAlign: "left",
    fontSize: 40,
    color: "",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 40,
  },
  addVariantPlus : {
    textAlign: "right",
    fontSize: 50,
    color: "green",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 60
  },
  addNotesPlus : {
    textAlign: "right",
    fontSize: 50,
    color: themeColor,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 60,
    marginTop: 10
  },
  addVariantPlusLeft : {
    textAlign: "left",
    fontSize: 50,
    color: "green",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 70
  },
  addNotesPlusLeft : {
    textAlign: "left",
    fontSize: 50,
    color: themeColor,
    fontStyle: "italic",
    fontWeight: "bold",
    marginTop: 10,
    height: 70
  },
  addVariantDone : {
    textAlignVertical: "bottom",
    textAlign: "right",
    fontSize: 100,
    color: "green",
    backgroundColor: "#98FB98",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 100
  },
  trash : {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "right",
    fontSize: 40,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 50,
    color: themeColor,
    flexDirection: "column",
    position: 'absolute',
    top: 5,
    left: 375,
    zIndex: 999
  },
  addVariantDoneUpper : {
    textAlignVertical: "bottom",
    textAlign: "right",
    fontSize: 100,
    color: "green",
    backgroundColor: "#98FB98",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 20
  },
  addVariantDoneBlue : {
    textAlignVertical: "bottom",
    textAlign: "right",
    fontSize: 100,
    color: "black",
    backgroundColor: "blue",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 100
  },
  addVariantPlus2 : {
    textAlign: "left",
    fontSize: 50,
    color: "blue",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 70
  },
  addVariantPlus2Right : {
    textAlign: "right",
    fontSize: 50,
    color: "blue",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 70
  },
  startButton: {
    textAlignVertical: "center",
    textAlign: "center",
    color: themeColor,
    fontSize: 80,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 100,
  },
  saveButton2: {
    textAlignVertical: "top",
    textAlign: "center",
    backgroundColor: "#98FB98",
    fontSize: 25,
    fontStyle: "italic",
    fontWeight: "bold",
  },
  saveButton3: {
    textAlignVertical: "top",
    textAlign: "center",
    color: "white",
    backgroundColor: "black",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1
  },
  fluentButton: {
    textAlignVertical: "top",
    textAlign: "center",
    color: "black",
    backgroundColor: themeColor,
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1
  },
  fluentRow: {
    textAlignVertical: "top",
    textAlign: "center",
    color: "#222222",
    backgroundColor: "black",
    fontSize: 50,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1
  },
  notesHeader: {
    textAlignVertical: "top",
    textAlign: "center",
    color: "white",
    backgroundColor: "black",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1,
    height: 40
  },
  highlighteableOption: {
    textAlignVertical: "top",
    textAlign: "center",
    color: "white",
    backgroundColor: "black",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1
  },
  bpmHeading: {
    textAlignVertical: "top",
    textAlign: "left",
    color: themeColor,
    backgroundColor: "black",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    marginRight: 30
  },
  bpmOption: {
    textAlignVertical: "top",
    textAlign: "center",
    color: "white",
    backgroundColor: "green",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    
  },
  highlighteableOptionGreen: {
    textAlignVertical: "top",
    textAlign: "center",
    color: "green",
    backgroundColor: "black",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1
  },
  fluentHeader: {
    textAlignVertical: "top",
    textAlign: "center",
    color: "black",
    backgroundColor: themeColor,
    fontSize: 50,
    marginBottom: 25,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1
  },
  variantAddSaveHeader: {
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 50,
    marginBottom: 0,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1,
    marginTop: 25
  },
  variantAddHeading: {
    textAlignVertical: "top",
    textAlign: "center",
    backgroundColor: themeColor,
    fontSize: 50,
    marginBottom: 20,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1,
    marginTop: 0,
  },
  variantAddCreateButton: {
    textAlignVertical: "top",
    textAlign: "center",
    color: "green",
    fontSize: 25,
    marginBottom: 12,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1,
    marginTop: 12
  },
  variantAddCreateButtonGrey: {
    textAlignVertical: "top",
    textAlign: "center",
    color: vsrs,
    fontSize: 25,
    marginBottom: 12,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1,
    marginTop: 12
  },
  saveButton3r: {
    textAlignVertical: "top",
    textAlign: "center",
    color: "#333333",
    backgroundColor: "white",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1
  },
  linkChoiceButton3: {
    textAlignVertical: "top",
    textAlign: "center",
    backgroundColor: "#98FB98",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1
  },
  linkButton3r: {
    textAlignVertical: "top",
    textAlign: "center",
    backgroundColor: "#000000",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    flexGrow: 1
  },
  goToStatsButton: {
    textAlignVertical: "top",
    textAlign: "center",
    color: themeColor,
    fontSize: 12,
    fontStyle: "italic",
    fontWeight: "bold",
  },
  addInstrumentButton: {
    textAlignVertical: "top",
    textAlign: "center",
    color: themeColor,
    fontSize: 12,
    top: 30,
    fontStyle: "italic",
    fontWeight: "bold",
  },
  groupScreenPathHeader: {
    top: 30,
    textAlign: "center",
    color: themeColor,
    fontSize: 15,
    fontStyle: "italic",
    fontWeight: "bold",
    marginBottom: 0
  },
  backButton: {
    textAlign: "left",
    color: themeColor,
    fontSize: 33,
    top: 30,
    height: 39,
    fontStyle: "italic",
    fontWeight: "bold"
  },
  backButtonButItsStats: {
    textAlignVertical: "top",
    textAlign: "right",
    color: themeColor,
    fontSize: 33,
    height: 39,
    fontStyle: "italic",
    fontWeight: "bold"
  },
  rightColumnOVariants: {
    textAlignVertical: "top",
    textAlign: "right",
    color: "black",
    fontSize: 33,
    height: 39,
    fontStyle: "italic",
    fontWeight: "bold"
  },
  addGroupButton: {
    textAlignVertical: "top",
    textAlign: "center",
    backgroundColor: "#1ca3ec",
    fontSize: 12,
    fontStyle: "italic",
    fontWeight: "bold",
  },
  addLessonButton: {
    textAlignVertical: "top",
    textAlign: "center",
    backgroundColor: "#2389da",
    fontSize: 89,
    fontStyle: "italic",
    fontWeight: "bold",
  },
  groupScreenTitle: {
    top: 30,
    textAlign: "center",
    color: "white",
    fontSize: 74,
    fontStyle: "italic",
    fontWeight: "bold",
    fontFamily: "optima"
  },
  enterButton: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 74,
    color: "#333333",
    fontStyle: "italic",
    fontWeight: "bold"
  },
  variantGroupTitle: {
    textAlignVertical: "center",
    textAlign: "left",
    fontSize: 30,
    color: "#333333",
    fontStyle: "italic",
    fontWeight: "bold"
  },
  addLessonOrGroupRow: {
    flexDirection:"row"
  },
  notesBackground: {
    backgroundColor: "black",
  },
  examplesRow: {
    flexDirection:"row",
    textAlign: "center",
    justifyContent: 'center',
    alignItems: 'center'
  },
  metronomeLabelAndPlayButtonRow: {
    flexDirection:"row",
    textAlign: "center",
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -20
  },
  challengeMetronomeMain: {
    flexDirection:"row",
    textAlign: "center",
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: themeColor,
    top: -20
  },
  challengeMetronomeSubheading: {
    flexDirection:"row",
    textAlign: "center",
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: themeColor,
    height: 140,
    top: -20
  },
  addLessonCol: {//unnerlated^
    flexDirection:"column",
    textAlign: "left"
  },
   challengeMetronomeColumn: {//unnerlated^
    flexDirection:"column",
    textAlign: "left",
    backgroundColor: themeColor
  },
  saveButton4: {
    textAlignVertical: "top",
    textAlign: "center",
    backgroundColor: "#98FB98",
    fontSize: 12,
    fontStyle: "italic",
    fontWeight: "bold",
  },
  saveButton5: {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 20,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 200,
    color: "#000000",
    flexDirection: "column",
  },
  saveButton6: {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "left",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 40,
    color: "#000000",
    flexDirection: "column",
  },
  saveButton7: {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "left",
    fontSize: 40,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 100,
    color: "#000000",
    flexDirection: "column",
    
  },
  criteriaTextInput: {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "left",
    fontSize: 40,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 60,
    color: "white",
    flexDirection: "column",

    textAlignVertical: "center",
    textAlign: "center",

    
  },
  criteriaTextInput4: {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "left",
    fontSize: 40,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 60,
    color: vsrs,
    flexDirection: "column",

    textAlignVertical: "center",
    textAlign: "center",

    
  },
  criteriaTextInputG: {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "left",
    fontSize: 40,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 60,
    color: "green",
    flexDirection: "column",

    textAlignVertical: "center",
    textAlign: "center",

    
  },
  goalTime: {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 37,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 45,
    flexDirection: "column",
    color: "white",
    
  },
  filterRow: {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "left",
    fontSize: 40,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 65,
    color: "white",
    backgroundColor: "black",
    flexDirection: "column"
  },
  filterOrCreate: {
    flexShrink: 1,
    textAlign: "left",
    fontSize: 22,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 22,
    color: "black",
    flexDirection: "column"
  },
  filterRowVA: {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "left",
    fontSize: 40,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 50,
    color: "white",
    backgroundColor: themeColor,
    flexDirection: "column"
  },
  snazzyCategorySubHeader: {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "left",
    fontSize: 40,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 65,
    color: "white",
    backgroundColor: "black",
    flexDirection: "column",
    color: themeColor

  },
  filterRowRight: {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "right",
    fontSize: 40,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 50,
    color: themeColor,
    backgroundColor: "black",
    flexDirection: "column",
    position: 'absolute',
    top: 130,
    left: 285
  },
  saveButton7NewKnown : {
    flexShrink: 1,
    textAlign: "left",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 40,
    color: "#000000",
    flexDirection: "row",
  },
  saveButton8NewKnown : {
    flexShrink: 1,
    textAlign: "right",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 40,
    color: "#000000",
    flexDirection: "row",
  },
  saveButton8: {
    flexShrink: 1,
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 28,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 40,
    color: "#000000",
    flexDirection: "column",
  },

  saveScreenSpacer: {
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 25,
    fontStyle: "italic",
    fontWeight: "bold",
  },
  lessonInfoScreenSpacer: {
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 25,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 300,
  },

  groupNames: {
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 89,
    fontStyle: "italic",
    fontWeight: "bold",
  },

  homescreenSpacer2: {
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 12,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 80,
  },

  groupOption: {
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 89,
    color: "#333333",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 110,
  },
  openLesson: {
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 89,
    color: "#333333",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 110,
  },
  openGroup: {
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 89,
    fontStyle: "italic",
    fontWeight: "bold",
    color: "#333333",
    backgroundColor: "black",
    height: 110,
  },
  homeScreenSpacer: {
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 25,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 90,
  },
  enterArrow: {
    textAlignVertical: "top",
    textAlign: "center",
    fontSize: 100,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 90,
  },
  saveLessonButton: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    color: themeColor,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 120,
  },
  examplesButton: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 40,
    color: "white",
  },
  actualExample: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    color: themeColor,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 100,
    marginLeft: -230,
  },
  addLessonExample: {
    textAlign: "center",
    fontSize: 100,
    color: themeColor,
    fontStyle: "italic",
    fontWeight: "bold",
    marginLeft: 30,
  },
  actualExampleB: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 50,
    color: "blue",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 70,
    marginLeft: 40,
  },
  addLessonExampleB: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 35,
    color: "blue",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 50,
    marginLeft: 40,
  },
    actualExampleG: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 50,
    color: "green",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 70,
  },
  addLessonExampleG: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 35,
    color: "green",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 50,
  },
  actualExampleO: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 60,
    color: themeColor,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 70,

  },
  actualExampleBO: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 30,
    color: "blue",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 70,

  },
    actualExampleGO: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 30,
    color: "green",
    fontStyle: "italic",
    fontWeight: "bold",
    height: 70,
  },
  addVariantGroupButton: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 29,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 180,
  },

  groupScreenSpacer: {
    textAlignVertical: "center",
    textAlign: "center",
  
    fontSize: 100,
    fontStyle: "italic",
    fontWeight: "bold",
    height: 500,
  },
  groupScreenBackground: {
   
  },
  homeScreenBackground: {
    
  },
  saveScreenBackground: {
  },
  lessonInfoScreenBackground: {
    height: 5000,
  },
  challengeScreenBackground: {
    height: 2000
  },
  challengeButton: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    color: "#333333",
    fontStyle: "italic",
    fontWeight: "bold",
  },
  challengeAutoButton: {
    top: -20,
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 80,
    color: "#333333",
    fontStyle: "italic",
    fontWeight: "bold",
  },
  challengeAutoButtonG: {
    top: -20,
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 80,
    color: "green",
    fontStyle: "italic",
    fontWeight: "bold",
  },
  challengeBpmChangeButtonVis: {
    top: -20,
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    color: "#333333",
    fontStyle: "italic",
    fontWeight: "bold",
  },
  challengeBpmChangeButtonInVis: {
    top: -20,
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    color: "#FFB6C1",
    fontStyle: "italic",
    fontWeight: "bold",
  },
  challengeBpmIndicatorInit: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 80,
    color: "#333333",
    fontStyle: "italic",
    fontWeight: "bold",
    paddingBottom: 10
  },
  challengeBpmIndicatorGreen: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 80,
    color: "green",
    fontStyle: "italic",
    fontWeight: "bold",
  },
  metronomeLabel: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 30,
    color: "#333333",
    fontStyle: "italic",
    fontWeight: "bold",
  },
  triesIndicator: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    color: "#333333",
    fontStyle: "italic",
    fontWeight: "bold",
    height: "100%",
  },
  triesLabel: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 70,
    color: "#333333",
    fontStyle: "italic",
    fontWeight: "bold",
    height: "100%",
    top: 30
  },
  challengePlusButton: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    color: themeColor,
    fontStyle: "italic",
    fontWeight: "bold",
  },
  challengeMinusButton: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    color: themeColor,
    fontStyle: "italic",
    fontWeight: "bold",
  },
  generateButton: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 75,
    color: "green",
    fontStyle: "italic",
    fontWeight: "bold",
    marginTop: 25
  },
  metronomePlayPauseButton: {
    textAlign: "center",
    fontSize: 45,
    color: "white",
    fontStyle: "italic",
    fontWeight: "bold",
    marginLeft: 30
  },
  addStuffButton: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    top: 10,
    color: "green",
    fontStyle: "italic",
    fontWeight: "bold",
  },
  smallerAddStuffButton: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 50,
    color: "green",
    fontStyle: "italic",
    fontWeight: "bold",
    backgroundColor: "black",
    flexDirection: "column",
  },
  smallerAddStuffButtonRed: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 50,
    color: "red",
    top: 20,
    fontStyle: "italic",
    fontWeight: "bold",
    backgroundColor: "black",
    flexDirection: "column",
  },
  addStuffButtonRed: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    top: 10,
    color: "red",
    fontStyle: "italic",
    fontWeight: "bold",
  },
  challengeButtonGreen: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 100,
    color: "green",
    fontStyle: "italic",
    fontWeight: "bold",
  },

  cri: {
    textAlignVertical: "center",
    textAlign: "auto",
    fontSize: 60,
    fontStyle: "italic",
    fontWeight: "bold",
  },
  challengeMetronomeButton: {
    width: "100%",
    height: "55%",
    paddingLeft: 50,
    paddingRight: 50,
    color: "white",
    textAlign: "center",
    fontSize: 50,
    fontStyle: "italic",
    fontWeight: "bold"
  },
  criWhite: {
    textAlignVertical: "center",
    textAlign: "auto",
    fontSize: 60,
    fontStyle: "italic",
    fontWeight: "bold",
    color: "white"
  },
  warningScreen: {
    textAlignVertical: "center",
    textAlign: "auto",
    fontSize: 11,
    fontWeight: "bold",
    color: "white",
    marginLeft: 25,
    marginRight: 10,
    marginTop: 400
  },
  warningScreen3: {
    textAlignVertical: "center",
    textAlign: "auto",
    fontSize: 11,
    fontWeight: "bold",
    color: "white",
    marginLeft: 25,
    marginRight: 10,
    marginTop: 20
  },
  warningScreenHeader: {
    textAlignVertical: "center",
    textAlign: "auto",
    fontSize: 33,
    fontWeight: "bold",
    color: "white",
    marginLeft: 25,
    marginRight: 10,
    marginTop: -300
  },
  warningScreen1: {
    textAlignVertical: "center",
    textAlign: "auto",
    fontSize: 11,
    fontWeight: "bold",
    color: "white",
    marginLeft: 25,
    marginRight: 10,
    marginTop: 40
  },
  warningScreenUnderstand: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: 33,
    fontWeight: "bold",
    color: "black",
    marginTop: 30,
    marginBottom: 120,
    width: 430,
    backgroundColor: themeColor
  },
  scrollStyle: {
  },
  challengeBorder: {
    top: -300,
    height: 880,
    width: 430,
    borderWidth: 20,
    borderColor: '#FFFFFF',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  l: {
    position: 'absolute',
    top: 60,
    left: 389,
    height: 710,
    width: 0,
    borderColor: 'black',
    borderLeftWidth: 20,
    borderTopWidth: 20,
  },
  r: {
    position: 'absolute',
    top: 60,
    left: -20,
    height: 710,
    width: 0,
    borderColor: 'black',
    borderLeftWidth: 20,
    borderTopWidth: 20,
  },
  b: {
    position: 'absolute',
    top: 820,
    left: 60,
    height: 0,
    width: 270,
    borderColor: 'black',
    borderLeftWidth: 20,
    borderTopWidth: 20,
  },
  b2: {
    position: 'absolute',
    top: 840,
    left: 60,
    height: 0,
    width: 270,
    borderColor: 'black',
    borderLeftWidth: 20,
    borderTopWidth: 20,
  },
  t: {
    position: 'absolute',
    top: -20,
    left: 60,
    height: 0,
    width: 270,
    borderColor: 'black',
    borderLeftWidth: 20,
    borderTopWidth: 20,
  },
  challengeBorderT: {
    height: 450,
    width: 430,
    borderWidth: 20,
    borderColor: '#FFFFFF',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  lT: {//this is right lol
    position: 'absolute',
    top: 60,
    left: 389,
    height: 300,
    width: 0,
    borderColor: 'black',
    borderLeftWidth: 20,
    borderTopWidth: 20,
  },
  rT: {//this is left lol
    position: 'absolute',
    top: 60,
    left: -20,
    height: 300,
    width: 0,
    borderColor: 'black',
    borderLeftWidth: 20,
    borderTopWidth: 20,
  },
  bT: {
    position: 'absolute',
    top: 409,
    left: 60,
    height: 0,
    width: 270,
    borderColor: 'black',
    borderLeftWidth: 20,
    borderTopWidth: 20,
  },
  bT2: {
    position: 'absolute',
    top: 411,
    left: 60,
    height: 0,
    width: 270,
    borderColor: 'black',
    borderLeftWidth: 20,
    borderTopWidth: 20,
  },
  tT: {
    position: 'absolute',
    top: -20,
    left: 60,
    height: 0,
    width: 270,
    borderColor: 'black',
    borderLeftWidth: 20,
    borderTopWidth: 20,
  },
  statsStyle1: {
    color: "white", 
    fontSize: 40, 
    marginTop: 50, 
    textAlign: "center", 
    fontStyle: "italic", 
    fontWeight: "bold"
  },
  statsStyle2: {
    color: "#222222", 
    fontSize: 30, 
    top: 3, 
    textAlign: "center", 
    fontStyle: "italic", 
    fontWeight: "bold"
  },
  statsStyle3: {
    color: "white", 
    fontSize: 30, 
    top: 3, 
    textAlign: "center", 
    fontStyle: "italic", 
    fontWeight: "bold"
  },
  statsStyle4: {
    color: "white", 
    fontSize: 40, 
    marginTop: 50, 
    textAlign: "center", 
    fontStyle: "italic", 
    fontWeight: "bold"
  }
});
